logo: https://static.thenounproject.com/png/2318530-200.png
clientId: 783262894504-rk14vg9ogq4fpsusf87lsubc8c644bni.apps.googleusercontent.com
scriptId: 14dxucr5SCH4th01ndHLdN4HA0civDnVqk4HR9lAfsWaPCr4mOnOZFa_c
menuUrl: https://script.google.com/macros/s/AKfycbwPOy2a-8rclTaY3MHLQp1P3Nk75Ot8hJ86zANML91mCOVMfA/exec?bookId=${book.id}&accountId=${account.id}
menuUrlDev: https://script.google.com/a/bkper.com/macros/s/AKfycbywpzjsUP7qAeDoAt-Jgs-Jc_pRRmxQnPnx1wgWKg/dev?bookId=${book.id}&accountId=${account.id}
menuText: Calculate Realized Results
menuPopupWidth: 500
menuPopupHeight: 300
scopes: >
    https://www.googleapis.com/auth/userinfo.email
    https://www.googleapis.com/auth/script.external_request

triggers: >
    onTransactionPosted
    onTransactionChecked
    onTransactionUnchecked
    onTransactionUpdated
    onTransactionDeleted
    onTransactionRestored
    onAccountCreated
    onAccountUpdated
    onAccountDeleted    
    onGroupCreated
    onGroupUpdated
    onGroupDeleted

properties: 
    transaction:
      keys: >
        quantity
        order
        interest
        fees
        instrument
        trade_date
        
    group:
      keys: >
        stock_exc_code

    account:
      keys: >
        stock_fees_account
        stock_unreal_account
        stock_gain_account
        stock_loss_account

apiVersion: v3
deploymentId: AKfycbwtsLZgfLUKpXPSQzDjjGMgJEkvwXN5CklmeCHtpEPpXDK66g
whitelist: >
    maelcaldas@gmail.com
    dgonzalez@ppv.com.uy
    ppvbkper@ppvbooks.com.uy
    ppvbkper@ppvbooks.com.uy
    brainbkper@ppvbooks.com.uy
